/* This file is automatically generated by Lemon from input grammar
** source file "lib/parser/syntaxis/opam_syntaxis.y". */
/*
** 2000-05-29
**
** The author disclaims copyright to this source code.  In place of
** a legal notice, here is a blessing:
**
**    May you do good and not evil.
**    May you find forgiveness for yourself and forgive others.
**    May you share freely, never taking more than you give.
**
*************************************************************************
** Driver template for the LEMON parser generator.
**
** The "lemon" program processes an LALR(1) input grammar file, then uses
** this template to construct a parser.  The "lemon" program inserts text
** at each "%%" line.  Also, any "P-a-r-s-e" identifer prefix (without the
** interstitial "-" characters) contained in this template is changed into
** the value of the %name directive from the grammar.  Otherwise, the content
** of this template is copied straight through into the generate parser
** source file.
**
** The following is the concatenation of all %include directives from the
** input grammar file:
*/
/************ Begin %include sections from the grammar ************************/
#line 4 "lib/parser/syntaxis/opam_syntaxis.y"

#include <assert.h>
#include <setjmp.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>

#include "utarray.h"
#include "uthash.h"

#include "liblogc.h"

#if INTERFACE
#ifndef YYMALLOCARGTYPE
#define YYMALLOCARGTYPE size_t
#endif
#endif

#define DEBUG_LEVEL debug_opamc_syntaxis
int  DEBUG_LEVEL;
#define TRACE_FLAG trace_opamc_syntaxis
bool TRACE_FLAG;

#line 29 "lib/parser/syntaxis/opam_syntaxis.y"

struct opam_arg_s *p;
#define DUMP_ARGS(args)                          \
    LOG_DEBUG(0, "DUMPING args", "");           \
    LOG_DEBUG(0, "args ct: %d",                 \
                  utarray_len(args));              \
    for(p=(struct opam_arg_s*)utarray_front(args); \
        p!=NULL;                                  \
        p=(struct opam_arg_s*)utarray_next(args,p)) {    \
       LOG_DEBUG(0, "\tval: %s, type: %d", p->val, p->t); \
     }
    /* while ( (p=(char**)utarray_next(tok.args,p))) { \ */
    /*     LOG_DEBUG(0, "\t%s",*p);             \ */
    /* } */
#line 68 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
#include "opam_syntaxis.h"
//lemp->filename "lib/parser/syntaxis/opam_syntaxis.y"
/**************** End of %include directives **********************************/
/* These constants specify the various numeric values for terminal symbols.
***************** Begin token definitions *************************************/
#if INTERFACE
#define AMP                             1
#define AUTHORS                         2
#define AVAILABLE                       3
#define BANG                            4
#define BUG_REPORTS                     5
#define Bool                            6
#define BUILD                           7
#define BUILD_DOC                       8
#define BUILD_ENV                       9
#define CmdListFld                     10
#define COLON                          11
#define COMMA                          12
#define CONFLICTS                      13
#define CONFLICT_CLASS                 14
#define DEPENDS                        15
#define DEPEXTS                        16
#define DEPOPTS                        17
#define DESCRIPTION                    18
#define DEV_REPO                       19
#define DOC                            20
#define DQ                             21
#define EQ                             22
#define ERROR                          23
#define EXTRA_FILES                    24
#define EXTRA_SOURCE                   25
#define FALSE                          26
#define FEATURES                       27
#define FLAG                           28
#define FLAGS                          29
#define FldName                        30
#define FVF_LOGOP                      31
#define HOMEPAGE                       32
#define IDENT                          33
#define IDENTCHAR                      34
#define INSTALL                        35
#define Int                            36
#define LBRACE                         37
#define LBRACKET                       38
#define LICENSE                        39
#define LogOp                          40
#define LPAREN                         41
#define MAINTAINER                     42
#define MESSAGES                       43
#define OPAM_VERSION                   44
#define PACKAGE                        45
#define PATCHES                        46
#define PIN_DEPENDS                    47
#define PKGNAME                        48
#define POST_MESSAGES                  49
#define QMARK                          50
#define RBRACE                         51
#define RBRACKET                       52
#define REMOVE                         53
#define RELOP                          54
#define RPAREN                         55
#define RUNTEST                        56
#define SETENV                         57
#define SQ                             58
#define String                         59
#define String3                        60
#define SUBSTS                         61
#define SYNOPSIS                       62
#define TAGS                           63
#define TERM                           64
#define TERM_STRING                    65
#define TERM_VARIDENT                  66
#define TQ                             67
#define TRUE                           68
#define URL                            69
#define Varident                       70
#define VERSION                        71
#endif
/**************** End token definitions ***************************************/

/* The next sections is a series of control #defines.
** various aspects of the generated parser.
**    YYCODETYPE         is the data type used to store the integer codes
**                       that represent terminal and non-terminal symbols.
**                       "unsigned char" is used if there are fewer than
**                       256 symbols.  Larger types otherwise.
**    YYNOCODE           is a number of type YYCODETYPE that is not used for
**                       any terminal or nonterminal symbol.
**    YYFALLBACK         If defined, this indicates that one or more tokens
**                       (also known as: "terminal symbols") have fall-back
**                       values which should be used if the original symbol
**                       would not parse.  This permits keywords to sometimes
**                       be used as identifiers, for example.
**    YYACTIONTYPE       is the data type used for "action codes" - numbers
**                       that indicate what to do in response to the next
**                       token.
**    ParseTOKENTYPE     is the data type used for minor type for terminal
**                       symbols.  Background: A "minor type" is a semantic
**                       value associated with a terminal or non-terminal
**                       symbols.  For example, for an "ID" terminal symbol,
**                       the minor type might be the name of the identifier.
**                       Each non-terminal can have a different minor type.
**                       Terminal symbols all have the same minor type, though.
**                       This macros defines the minor type for terminal 
**                       symbols.
**    YYMINORTYPE        is the data type used for all minor types.
**                       This is typically a union of many types, one of
**                       which is ParseTOKENTYPE.  The entry in the union
**                       for terminal symbols is called "yy0".
**    YYSTACKDEPTH       is the maximum depth of the parser's stack.  If
**                       zero the stack is dynamically sized using realloc()
**    ParseARG_SDECL     A static variable declaration for the %extra_argument
**    ParseARG_PDECL     A parameter declaration for the %extra_argument
**    ParseARG_PARAM     Code to pass %extra_argument as a subroutine parameter
**    ParseARG_STORE     Code to store %extra_argument into yypParser
**    ParseARG_FETCH     Code to extract %extra_argument from yypParser
**    ParseCTX_*         As ParseARG_ except for %extra_context
**    YYERRORSYMBOL      is the code number of the error symbol.  If not
**                       defined, then do no error processing.
**    YYNSTATE           the combined number of states.
**    YYNRULE            the number of rules in the grammar
**    YYNTOKEN           Number of terminal symbols
**    YY_MAX_SHIFT       Maximum value for shift actions
**    YY_MIN_SHIFTREDUCE Minimum value for shift-reduce actions
**    YY_MAX_SHIFTREDUCE Maximum value for shift-reduce actions
**    YY_ERROR_ACTION    The yy_action[] code for syntax error
**    YY_ACCEPT_ACTION   The yy_action[] code for accept
**    YY_NO_ACTION       The yy_action[] code for no-op
**    YY_MIN_REDUCE      Minimum value for reduce actions
**    YY_MAX_REDUCE      Maximum value for reduce actions
*/
#ifndef INTERFACE
# define INTERFACE 1
#endif
/************* Begin control #defines *****************************************/
#define YYCODETYPE unsigned char
#define YYNOCODE 90
#define YYACTIONTYPE unsigned char
#if INTERFACE
#define ParseTOKENTYPE  union opam_token_u 
#endif
typedef union {
  int yyinit;
  ParseTOKENTYPE yy0;
  struct opam_binding_s * yy29;
  UT_array * yy62;
  struct opam_package_s * yy86;
  struct opam_deps_s * yy170;
} YYMINORTYPE;
#ifndef YYSTACKDEPTH
#define YYSTACKDEPTH 100
#endif
#if INTERFACE
#define ParseARG_SDECL  struct opam_parse_state_s *opam_parse_state ;
#define ParseARG_PDECL , struct opam_parse_state_s *opam_parse_state 
#define ParseARG_PARAM ,opam_parse_state 
#define ParseARG_FETCH  struct opam_parse_state_s *opam_parse_state =yypParser->opam_parse_state ;
#define ParseARG_STORE yypParser->opam_parse_state =opam_parse_state ;
#define ParseCTX_SDECL
#define ParseCTX_PDECL
#define ParseCTX_PARAM
#define ParseCTX_FETCH
#define ParseCTX_STORE
#endif
#define YYNSTATE             84
#define YYNRULE              46
#define YYNRULE_WITH_ACTION  46
#define YYNTOKEN             72
#define YY_MAX_SHIFT         83
#define YY_MIN_SHIFTREDUCE   84
#define YY_MAX_SHIFTREDUCE   129
#define YY_ERROR_ACTION      130
#define YY_ACCEPT_ACTION     131
#define YY_NO_ACTION         132
#define YY_MIN_REDUCE        133
#define YY_MAX_REDUCE        178
/************* End control #defines *******************************************/
#define YY_NLOOKAHEAD ((int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])))

/* Define the yytestcase() macro to be a no-op if is not already defined
** otherwise.
**
** Applications can choose to define yytestcase() in the %include section
** to a macro that can assist in verifying code coverage.  For production
** code the yytestcase() macro should be turned off.  But it is useful
** for testing.
*/
#ifndef yytestcase
# define yytestcase(X)
#endif


/* Next are the tables used to determine what action to take based on the
** current state and lookahead token.  These tables are used to implement
** functions that take a state number and lookahead value and return an
** action integer.  
**
** Suppose the action integer is N.  Then the action is determined as
** follows
**
**   0 <= N <= YY_MAX_SHIFT             Shift N.  That is, push the lookahead
**                                      token onto the stack and goto state N.
**
**   N between YY_MIN_SHIFTREDUCE       Shift to an arbitrary state then
**     and YY_MAX_SHIFTREDUCE           reduce by rule N-YY_MIN_SHIFTREDUCE.
**
**   N == YY_ERROR_ACTION               A syntax error has occurred.
**
**   N == YY_ACCEPT_ACTION              The parser accepts its input.
**
**   N == YY_NO_ACTION                  No such action.  Denotes unused
**                                      slots in the yy_action[] table.
**
**   N between YY_MIN_REDUCE            Reduce by rule N-YY_MIN_REDUCE
**     and YY_MAX_REDUCE
**
** The action table is constructed as a single large table named yy_action[].
** Given state S and lookahead X, the action is computed as either:
**
**    (A)   N = yy_action[ yy_shift_ofst[S] + X ]
**    (B)   N = yy_default[S]
**
** The (A) formula is preferred.  The B formula is used instead if
** yy_lookahead[yy_shift_ofst[S]+X] is not equal to X.
**
** The formulas above are for computing the action when the lookahead is
** a terminal symbol.  If the lookahead is a non-terminal (as occurs after
** a reduce action) then the yy_reduce_ofst[] array is used in place of
** the yy_shift_ofst[] array.
**
** The following are the tables generated in this section:
**
**  yy_action[]        A single table containing all actions.
**  yy_lookahead[]     A table containing the lookahead for each entry in
**                     yy_action.  Used to detect hash collisions.
**  yy_shift_ofst[]    For each state, the offset into yy_action for
**                     shifting terminals.
**  yy_reduce_ofst[]   For each state, the offset into yy_action for
**                     shifting non-terminals after a reduce.
**  yy_default[]       Default action for each state.
**
*********** Begin parsing tables **********************************************/
#define YY_ACTTAB_COUNT (315)
static const YYACTIONTYPE yy_action[] = {
 /*     0 */   133,  134,  131,   30,   61,   58,   10,   53,   58,   41,
 /*    10 */    80,  134,  152,   75,  134,   77,  134,   54,   58,   59,
 /*    20 */    58,   43,  152,   60,   58,  152,    7,  152,  151,   47,
 /*    30 */    73,  134,   62,   58,   13,   79,  134,   28,  151,  141,
 /*    40 */   140,  151,  152,  151,    6,  144,   18,  152,   64,  141,
 /*    50 */   140,  139,  141,  140,  141,  140,   78,  134,  151,  144,
 /*    60 */    19,  139,   64,  151,  139,    8,  139,  178,  152,  141,
 /*    70 */   140,   48,   51,   67,  141,  140,  164,  178,  177,  138,
 /*    80 */   178,  139,  178,   65,  151,   40,  139,    8,  177,  138,
 /*    90 */   137,  177,  138,  177,  138,  141,  140,  178,   42,   15,
 /*   100 */   137,   66,  178,  137,   45,  137,  136,  139,  177,  138,
 /*   110 */    21,  156,    3,  177,  138,    5,  136,  135,  156,  136,
 /*   120 */   137,  136,  156,  178,   68,  137,   46,  135,   80,    4,
 /*   130 */   135,   75,  135,   77,  177,  138,  136,   12,   20,   22,
 /*   140 */    24,  136,  142,   26,   57,   11,  137,  135,   73,    1,
 /*   150 */    12,   33,  135,   79,  162,   82,  142,    9,    2,   39,
 /*   160 */   160,  160,  136,   37,   34,  162,   12,   56,  160,  161,
 /*   170 */   161,   14,  160,  135,   78,  160,   72,  161,   55,   16,
 /*   180 */    35,  161,  159,  159,  161,   63,    6,  158,  158,   20,
 /*   190 */   159,  167,  167,   70,  159,  158,   11,  159,  166,  158,
 /*   200 */    31,   17,  158,   21,  157,  146,  167,  150,   50,  166,
 /*   210 */   149,  157,   74,  167,  153,  157,   21,   76,  157,   49,
 /*   220 */   146,  153,  150,  165,  167,  149,  148,  146,  163,  150,
 /*   230 */   147,   44,  149,   36,  165,  175,   23,   25,  146,  163,
 /*   240 */   150,  148,  174,  149,  155,  147,  175,  173,  148,  175,
 /*   250 */   175,  155,  147,  174,  172,  155,    4,  174,  173,  148,
 /*   260 */   171,    4,  173,  147,   81,  172,  170,   27,  172,  172,
 /*   270 */    69,  171,  132,  169,  171,  171,  132,  170,  132,  176,
 /*   280 */   170,  170,  132,   29,  169,   20,    5,  169,  169,    5,
 /*   290 */   176,  145,   11,    4,  176,  143,   32,  168,  132,  154,
 /*   300 */     4,  168,  132,    4,   52,  145,  154,   38,  132,  143,
 /*   310 */   132,  132,   83,  132,   71,
};
static const YYCODETYPE yy_lookahead[] = {
 /*     0 */     0,    0,   72,   73,   88,   89,   76,   88,   89,   73,
 /*    10 */    10,   10,    0,   13,   13,   15,   15,   88,   89,   88,
 /*    20 */    89,   84,   10,   88,   89,   13,   80,   15,    0,   74,
 /*    30 */    30,   30,   88,   89,   83,   35,   35,   11,   10,    0,
 /*    40 */     0,   13,   30,   15,   37,   38,   85,   35,   87,   10,
 /*    50 */    10,    0,   13,   13,   15,   15,   56,   56,   30,   52,
 /*    60 */    85,   10,   87,   35,   13,   40,   15,    0,   56,   30,
 /*    70 */    30,   81,   82,   81,   35,   35,   51,   10,    0,    0,
 /*    80 */    13,   30,   15,   86,   56,   59,   35,   40,   10,   10,
 /*    90 */     0,   13,   13,   15,   15,   56,   56,   30,   51,   83,
 /*   100 */    10,   74,   35,   13,   74,   15,    0,   56,   30,   30,
 /*   110 */    40,   41,    4,   35,   35,   40,   10,    0,   48,   13,
 /*   120 */    30,   15,   52,   56,   79,   35,   51,   10,   10,   54,
 /*   130 */    13,   13,   15,   15,   56,   56,   30,   38,   41,   78,
 /*   140 */    78,   35,   38,   78,   36,   48,   56,   30,   30,   41,
 /*   150 */    38,   52,   35,   35,   40,   59,   52,   37,   50,   77,
 /*   160 */    40,   41,   56,   67,   52,   51,   38,   59,   48,   40,
 /*   170 */    41,   38,   52,   56,   56,   55,   75,   48,   70,   38,
 /*   180 */    52,   52,   40,   41,   55,   71,   37,   40,   41,   41,
 /*   190 */    48,   37,   38,   59,   52,   48,   48,   55,   40,   52,
 /*   200 */    52,   52,   55,   40,   41,   37,   52,   37,   59,   51,
 /*   210 */    37,   48,   11,   59,   52,   52,   40,   11,   55,   70,
 /*   220 */    52,   59,   52,   40,   70,   52,   37,   59,   40,   59,
 /*   230 */    37,   55,   59,   67,   51,   40,   38,   38,   70,   51,
 /*   240 */    70,   52,   40,   70,   41,   52,   51,   40,   59,   54,
 /*   250 */    55,   48,   59,   51,   40,   52,   54,   55,   51,   70,
 /*   260 */    40,   54,   55,   70,   60,   51,   40,   38,   54,   55,
 /*   270 */    60,   51,   90,   40,   54,   55,   90,   51,   90,   40,
 /*   280 */    54,   55,   90,   38,   51,   41,   40,   54,   55,   40,
 /*   290 */    51,   38,   48,   54,   55,   38,   52,   51,   90,   52,
 /*   300 */    54,   55,   90,   54,   55,   52,   59,   52,   90,   52,
 /*   310 */    90,   90,   67,   90,   59,   90,   90,   90,   90,   90,
 /*   320 */    90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
 /*   330 */    90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
 /*   340 */    90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
 /*   350 */    90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
 /*   360 */    90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
 /*   370 */    90,   90,   90,   90,   90,   90,   90,   90,   90,   90,
 /*   380 */    72,   72,   72,   72,   72,   72,   72,
};
#define YY_SHIFT_COUNT    (83)
#define YY_SHIFT_MIN      (0)
#define YY_SHIFT_MAX      (257)
static const unsigned short int yy_shift_ofst[] = {
 /*     0 */   118,  108,  108,  108,  108,  108,  108,  149,  114,  114,
 /*    10 */     0,  120,  168,  148,  203,  244,  203,    7,   25,   47,
 /*    20 */    97,   97,   99,  104,  112,  104,  128,  104,  245,  134,
 /*    30 */     1,   12,   28,   39,   40,   51,   67,   78,   79,   90,
 /*    40 */   106,  117,  129,  142,  147,  163,  154,   70,  170,  173,
 /*    50 */   189,  193,  195,  202,  207,  214,  220,  226,  233,  239,
 /*    60 */   246,  249,   75,  158,  183,  188,  176,  253,  257,   96,
 /*    70 */   162,  247,  255,   26,  133,  201,  141,  206,  198,  199,
 /*    80 */   229,  166,  204,  210,
};
#define YY_REDUCE_COUNT (29)
#define YY_REDUCE_MIN   (-84)
#define YY_REDUCE_MAX   (101)
static const signed char yy_reduce_ofst[] = {
 /*     0 */   -70,  -84,  -81,  -71,  -69,  -65,  -56,  -10,  -39,  -25,
 /*    10 */   -64,  -63,  -54,  -45,  -49,  -45,   16,   -8,   -3,   -3,
 /*    20 */    27,   30,   45,   61,   45,   62,   45,   65,   82,  101,
};
static const YYACTIONTYPE yy_default[] = {
 /*     0 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    10 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    20 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    30 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    40 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    50 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    60 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    70 */   130,  130,  130,  130,  130,  130,  130,  130,  130,  130,
 /*    80 */   130,  130,  130,  130,
};
/********** End of lemon-generated parsing tables *****************************/

/* The next table maps tokens (terminal symbols) into fallback tokens.  
** If a construct like the following:
** 
**      %fallback ID X Y Z.
**
** appears in the grammar, then ID becomes a fallback token for X, Y,
** and Z.  Whenever one of the tokens X, Y, or Z is input to the parser
** but it does not parse, the type of the token is changed to ID and
** the parse is retried before an error is thrown.
**
** This feature can be used, for example, to cause some keywords in a language
** to revert to identifiers if they keyword does not apply in the context where
** it appears.
*/
#ifdef YYFALLBACK
static const YYCODETYPE yyFallback[] = {
};
#endif /* YYFALLBACK */

/* The following structure represents a single element of the
** parser's stack.  Information stored includes:
**
**   +  The state number for the parser at this level of the stack.
**
**   +  The value of the token stored at this level of the stack.
**      (In other words, the "major" token.)
**
**   +  The semantic value stored at this level of the stack.  This is
**      the information used by the action routines in the grammar.
**      It is sometimes called the "minor" token.
**
** After the "shift" half of a SHIFTREDUCE action, the stateno field
** actually contains the reduce action for the second half of the
** SHIFTREDUCE.
*/
struct yyStackEntry {
  YYACTIONTYPE stateno;  /* The state-number, or reduce action in SHIFTREDUCE */
  YYCODETYPE major;      /* The major token value.  This is the code
                         ** number for the token at this stack level */
  YYMINORTYPE minor;     /* The user-supplied minor token value.  This
                         ** is the value of the token  */
};
typedef struct yyStackEntry yyStackEntry;

/* The state of the parser is completely contained in an instance of
** the following structure */
struct yyParser {
  yyStackEntry *yytos;          /* Pointer to top element of the stack */
#ifdef YYTRACKMAXSTACKDEPTH
  int yyhwm;                    /* High-water mark of the stack */
#endif
#ifndef YYNOERRORRECOVERY
  int yyerrcnt;                 /* Shifts left before out of the error */
#endif
  ParseARG_SDECL                /* A place to hold %extra_argument */
  ParseCTX_SDECL                /* A place to hold %extra_context */
#if YYSTACKDEPTH<=0
  int yystksz;                  /* Current side of the stack */
  yyStackEntry *yystack;        /* The parser's stack */
  yyStackEntry yystk0;          /* First stack entry */
#else
  yyStackEntry yystack[YYSTACKDEPTH];  /* The parser's stack */
  yyStackEntry *yystackEnd;            /* Last entry in the stack */
#endif
};
typedef struct yyParser yyParser;

#ifndef NDEBUG
#include <stdio.h>
#include <assert.h>
static FILE *yyTraceFILE = 0;
static char *yyTracePrompt = 0;
#endif /* NDEBUG */

#ifndef NDEBUG
/* 
** Turn parser tracing on by giving a stream to which to write the trace
** and a prompt to preface each trace message.  Tracing is turned off
** by making either argument NULL 
**
** Inputs:
** <ul>
** <li> A FILE* to which trace output should be written.
**      If NULL, then tracing is turned off.
** <li> A prefix string written at the beginning of every
**      line of trace output.  If NULL, then tracing is
**      turned off.
** </ul>
**
** Outputs:
** None.
*/
void ParseTrace(FILE *TraceFILE, char *zTracePrompt){
  yyTraceFILE = TraceFILE;
  yyTracePrompt = zTracePrompt;
  if( yyTraceFILE==0 ) yyTracePrompt = 0;
  else if( yyTracePrompt==0 ) yyTraceFILE = 0;
}
#endif /* NDEBUG */

#if defined(YYCOVERAGE) || !defined(NDEBUG)
/* For tracing shifts, the names of all terminals and nonterminals
** are required.  The following table supplies these names */
static const char *const yyTokenName[] = { 
  /*    0 */ "$",
  /*    1 */ "AMP",
  /*    2 */ "AUTHORS",
  /*    3 */ "AVAILABLE",
  /*    4 */ "BANG",
  /*    5 */ "BUG_REPORTS",
  /*    6 */ "Bool",
  /*    7 */ "BUILD",
  /*    8 */ "BUILD_DOC",
  /*    9 */ "BUILD_ENV",
  /*   10 */ "CmdListFld",
  /*   11 */ "COLON",
  /*   12 */ "COMMA",
  /*   13 */ "CONFLICTS",
  /*   14 */ "CONFLICT_CLASS",
  /*   15 */ "DEPENDS",
  /*   16 */ "DEPEXTS",
  /*   17 */ "DEPOPTS",
  /*   18 */ "DESCRIPTION",
  /*   19 */ "DEV_REPO",
  /*   20 */ "DOC",
  /*   21 */ "DQ",
  /*   22 */ "EQ",
  /*   23 */ "ERROR",
  /*   24 */ "EXTRA_FILES",
  /*   25 */ "EXTRA_SOURCE",
  /*   26 */ "FALSE",
  /*   27 */ "FEATURES",
  /*   28 */ "FLAG",
  /*   29 */ "FLAGS",
  /*   30 */ "FldName",
  /*   31 */ "FVF_LOGOP",
  /*   32 */ "HOMEPAGE",
  /*   33 */ "IDENT",
  /*   34 */ "IDENTCHAR",
  /*   35 */ "INSTALL",
  /*   36 */ "Int",
  /*   37 */ "LBRACE",
  /*   38 */ "LBRACKET",
  /*   39 */ "LICENSE",
  /*   40 */ "LogOp",
  /*   41 */ "LPAREN",
  /*   42 */ "MAINTAINER",
  /*   43 */ "MESSAGES",
  /*   44 */ "OPAM_VERSION",
  /*   45 */ "PACKAGE",
  /*   46 */ "PATCHES",
  /*   47 */ "PIN_DEPENDS",
  /*   48 */ "PKGNAME",
  /*   49 */ "POST_MESSAGES",
  /*   50 */ "QMARK",
  /*   51 */ "RBRACE",
  /*   52 */ "RBRACKET",
  /*   53 */ "REMOVE",
  /*   54 */ "RELOP",
  /*   55 */ "RPAREN",
  /*   56 */ "RUNTEST",
  /*   57 */ "SETENV",
  /*   58 */ "SQ",
  /*   59 */ "String",
  /*   60 */ "String3",
  /*   61 */ "SUBSTS",
  /*   62 */ "SYNOPSIS",
  /*   63 */ "TAGS",
  /*   64 */ "TERM",
  /*   65 */ "TERM_STRING",
  /*   66 */ "TERM_VARIDENT",
  /*   67 */ "TQ",
  /*   68 */ "TRUE",
  /*   69 */ "URL",
  /*   70 */ "Varident",
  /*   71 */ "VERSION",
  /*   72 */ "package",
  /*   73 */ "binding",
  /*   74 */ "fpf",
  /*   75 */ "stringlist",
  /*   76 */ "bindings",
  /*   77 */ "string3",
  /*   78 */ "cmdlist",
  /*   79 */ "cmd",
  /*   80 */ "args",
  /*   81 */ "filter",
  /*   82 */ "arg",
  /*   83 */ "filtered_package_formulas",
  /*   84 */ "fvf_expr",
  /*   85 */ "fvf",
  /*   86 */ "logop_fvf",
  /*   87 */ "fvf_base",
  /*   88 */ "pred",
  /*   89 */ "pterm",
};
#endif /* defined(YYCOVERAGE) || !defined(NDEBUG) */

#ifndef NDEBUG
/* For tracing reduce actions, the names of all rules are required.
*/
static const char *const yyRuleName[] = {
 /*   0 */ "package ::= bindings",
 /*   1 */ "bindings ::= binding",
 /*   2 */ "bindings ::= bindings binding",
 /*   3 */ "binding ::= FldName String",
 /*   4 */ "binding ::= FldName COLON string3",
 /*   5 */ "binding ::= FldName COLON LBRACKET stringlist RBRACKET",
 /*   6 */ "binding ::= CmdListFld LBRACKET cmdlist RBRACKET",
 /*   7 */ "binding ::= INSTALL LBRACKET cmdlist RBRACKET",
 /*   8 */ "binding ::= RUNTEST LBRACKET cmdlist RBRACKET",
 /*   9 */ "cmdlist ::=",
 /*  10 */ "cmdlist ::= cmdlist cmd",
 /*  11 */ "cmd ::= LBRACKET args RBRACKET",
 /*  12 */ "cmd ::= LBRACKET args RBRACKET filter",
 /*  13 */ "args ::=",
 /*  14 */ "args ::= args arg",
 /*  15 */ "arg ::= String",
 /*  16 */ "arg ::= Varident",
 /*  17 */ "arg ::= filter",
 /*  18 */ "binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET",
 /*  19 */ "binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET",
 /*  20 */ "stringlist ::= String",
 /*  21 */ "stringlist ::= stringlist String",
 /*  22 */ "filtered_package_formulas ::=",
 /*  23 */ "filtered_package_formulas ::= filtered_package_formulas fpf",
 /*  24 */ "fpf ::= fpf LogOp fpf",
 /*  25 */ "fpf ::= LPAREN fpf RPAREN",
 /*  26 */ "fpf ::= PKGNAME fvf_expr",
 /*  27 */ "fpf ::= PKGNAME",
 /*  28 */ "fvf_expr ::= LBRACE fvf RBRACE",
 /*  29 */ "fvf ::=",
 /*  30 */ "fvf ::= fvf logop_fvf",
 /*  31 */ "logop_fvf ::= LogOp fvf",
 /*  32 */ "fvf ::= fvf_base",
 /*  33 */ "fvf_base ::= VERSION",
 /*  34 */ "filter ::= LBRACE pred RBRACE",
 /*  35 */ "pred ::= pred LogOp pred",
 /*  36 */ "pred ::= pterm",
 /*  37 */ "pterm ::= Int",
 /*  38 */ "pred ::= String",
 /*  39 */ "pterm ::= Varident",
 /*  40 */ "pred ::= BANG pred",
 /*  41 */ "pred ::= QMARK pred",
 /*  42 */ "pred ::= LPAREN pred RPAREN",
 /*  43 */ "pred ::= pred RELOP pred",
 /*  44 */ "string3 ::= TQ String3 TQ",
 /*  45 */ "string3 ::= TQ String3 String String3 TQ",
};
#endif /* NDEBUG */


#if YYSTACKDEPTH<=0
/*
** Try to increase the size of the parser stack.  Return the number
** of errors.  Return 0 on success.
*/
static int yyGrowStack(yyParser *p){
  int newSize;
  int idx;
  yyStackEntry *pNew;

  newSize = p->yystksz*2 + 100;
  idx = p->yytos ? (int)(p->yytos - p->yystack) : 0;
  if( p->yystack==&p->yystk0 ){
    pNew = malloc(newSize*sizeof(pNew[0]));
    if( pNew ) pNew[0] = p->yystk0;
  }else{
    pNew = realloc(p->yystack, newSize*sizeof(pNew[0]));
  }
  if( pNew ){
    p->yystack = pNew;
    p->yytos = &p->yystack[idx];
#ifndef NDEBUG
    if( yyTraceFILE ){
      fprintf(yyTraceFILE,"%sStack grows from %d to %d entries.\n",
              yyTracePrompt, p->yystksz, newSize);
    }
#endif
    p->yystksz = newSize;
  }
  return pNew==0; 
}
#endif

/* Datatype of the argument to the memory allocated passed as the
** second argument to ParseAlloc() below.  This can be changed by
** putting an appropriate #define in the %include section of the input
** grammar.
*/
#ifndef YYMALLOCARGTYPE
# define YYMALLOCARGTYPE size_t
#endif

/* Initialize a new parser that has already been allocated.
*/
void ParseInit(void *yypRawParser ParseCTX_PDECL){
  yyParser *yypParser = (yyParser*)yypRawParser;
  ParseCTX_STORE
#ifdef YYTRACKMAXSTACKDEPTH
  yypParser->yyhwm = 0;
#endif
#if YYSTACKDEPTH<=0
  yypParser->yytos = NULL;
  yypParser->yystack = NULL;
  yypParser->yystksz = 0;
  if( yyGrowStack(yypParser) ){
    yypParser->yystack = &yypParser->yystk0;
    yypParser->yystksz = 1;
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  yypParser->yytos = yypParser->yystack;
  yypParser->yystack[0].stateno = 0;
  yypParser->yystack[0].major = 0;
#if YYSTACKDEPTH>0
  yypParser->yystackEnd = &yypParser->yystack[YYSTACKDEPTH-1];
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** This function allocates a new parser.
** The only argument is a pointer to a function which works like
** malloc.
**
** Inputs:
** A pointer to the function used to allocate memory.
**
** Outputs:
** A pointer to a parser.  This pointer is used in subsequent calls
** to Parse and ParseFree.
*/
void *ParseAlloc(void *(*mallocProc)(YYMALLOCARGTYPE) ParseCTX_PDECL){
  yyParser *yypParser;
  yypParser = (yyParser*)(*mallocProc)( (YYMALLOCARGTYPE)sizeof(yyParser) );
  if( yypParser ){
    ParseCTX_STORE
    ParseInit(yypParser ParseCTX_PARAM);
  }
  return (void*)yypParser;
}
#endif /* Parse_ENGINEALWAYSONSTACK */


/* The following function deletes the "minor type" or semantic value
** associated with a symbol.  The symbol can be either a terminal
** or nonterminal. "yymajor" is the symbol code, and "yypminor" is
** a pointer to the value to be deleted.  The code used to do the 
** deletions is derived from the %destructor and/or %token_destructor
** directives of the input grammar.
*/
static void yy_destructor(
  yyParser *yypParser,    /* The parser */
  YYCODETYPE yymajor,     /* Type code for object to destroy */
  YYMINORTYPE *yypminor   /* The object to be destroyed */
){
  ParseARG_FETCH
  ParseCTX_FETCH
  switch( yymajor ){
    /* Here is inserted the actions which take place when a
    ** terminal or non-terminal is destroyed.  This can happen
    ** when the symbol is popped from the stack during a
    ** reduce or during error processing or when a parser is 
    ** being destroyed before it is finished parsing.
    **
    ** Note: during a reduce, the only symbols destroyed are those
    ** which appear on the RHS of the rule, but which are *not* used
    ** inside the C code.
    */
/********* Begin destructor definitions ***************************************/
/********* End destructor definitions *****************************************/
    default:  break;   /* If no destructor action specified: do nothing */
  }
}

/*
** Pop the parser's stack once.
**
** If there is a destructor routine associated with the token which
** is popped from the stack, then call it.
*/
static void yy_pop_parser_stack(yyParser *pParser){
  yyStackEntry *yytos;
  assert( pParser->yytos!=0 );
  assert( pParser->yytos > pParser->yystack );
  yytos = pParser->yytos--;
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sPopping %s\n",
      yyTracePrompt,
      yyTokenName[yytos->major]);
  }
#endif
  yy_destructor(pParser, yytos->major, &yytos->minor);
}

/*
** Clear all secondary memory allocations from the parser
*/
void ParseFinalize(void *p){
  yyParser *pParser = (yyParser*)p;
  while( pParser->yytos>pParser->yystack ) yy_pop_parser_stack(pParser);
#if YYSTACKDEPTH<=0
  if( pParser->yystack!=&pParser->yystk0 ) free(pParser->yystack);
#endif
}

#ifndef Parse_ENGINEALWAYSONSTACK
/* 
** Deallocate and destroy a parser.  Destructors are called for
** all stack elements before shutting the parser down.
**
** If the YYPARSEFREENEVERNULL macro exists (for example because it
** is defined in a %include section of the input grammar) then it is
** assumed that the input pointer is never NULL.
*/
void ParseFree(
  void *p,                    /* The parser to be deleted */
  void (*freeProc)(void*)     /* Function used to reclaim memory */
){
#ifndef YYPARSEFREENEVERNULL
  if( p==0 ) return;
#endif
  ParseFinalize(p);
  (*freeProc)(p);
}
#endif /* Parse_ENGINEALWAYSONSTACK */

/*
** Return the peak depth of the stack for a parser.
*/
#ifdef YYTRACKMAXSTACKDEPTH
int ParseStackPeak(void *p){
  yyParser *pParser = (yyParser*)p;
  return pParser->yyhwm;
}
#endif

/* This array of booleans keeps track of the parser statement
** coverage.  The element yycoverage[X][Y] is set when the parser
** is in state X and has a lookahead token Y.  In a well-tested
** systems, every element of this matrix should end up being set.
*/
#if defined(YYCOVERAGE)
static unsigned char yycoverage[YYNSTATE][YYNTOKEN];
#endif

/*
** Write into out a description of every state/lookahead combination that
**
**   (1)  has not been used by the parser, and
**   (2)  is not a syntax error.
**
** Return the number of missed state/lookahead combinations.
*/
#if defined(YYCOVERAGE)
int ParseCoverage(FILE *out){
  int stateno, iLookAhead, i;
  int nMissed = 0;
  for(stateno=0; stateno<YYNSTATE; stateno++){
    i = yy_shift_ofst[stateno];
    for(iLookAhead=0; iLookAhead<YYNTOKEN; iLookAhead++){
      if( yy_lookahead[i+iLookAhead]!=iLookAhead ) continue;
      if( yycoverage[stateno][iLookAhead]==0 ) nMissed++;
      if( out ){
        fprintf(out,"State %d lookahead %s %s\n", stateno,
                yyTokenName[iLookAhead],
                yycoverage[stateno][iLookAhead] ? "ok" : "missed");
      }
    }
  }
  return nMissed;
}
#endif

/*
** Find the appropriate action for a parser given the terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_shift_action(
  YYCODETYPE iLookAhead,    /* The look-ahead token */
  YYACTIONTYPE stateno      /* Current state number */
){
  int i;

  if( stateno>YY_MAX_SHIFT ) return stateno;
  assert( stateno <= YY_SHIFT_COUNT );
#if defined(YYCOVERAGE)
  yycoverage[stateno][iLookAhead] = 1;
#endif
  do{
    i = yy_shift_ofst[stateno];
    assert( i>=0 );
    assert( i<=YY_ACTTAB_COUNT );
    assert( i+YYNTOKEN<=(int)YY_NLOOKAHEAD );
    assert( iLookAhead!=YYNOCODE );
    assert( iLookAhead < YYNTOKEN );
    i += iLookAhead;
    assert( i<(int)YY_NLOOKAHEAD );
    if( yy_lookahead[i]!=iLookAhead ){
#ifdef YYFALLBACK
      YYCODETYPE iFallback;            /* Fallback token */
      assert( iLookAhead<sizeof(yyFallback)/sizeof(yyFallback[0]) );
      iFallback = yyFallback[iLookAhead];
      if( iFallback!=0 ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE, "%sFALLBACK %s => %s\n",
             yyTracePrompt, yyTokenName[iLookAhead], yyTokenName[iFallback]);
        }
#endif
        assert( yyFallback[iFallback]==0 ); /* Fallback loop must terminate */
        iLookAhead = iFallback;
        continue;
      }
#endif
#ifdef YYWILDCARD
      {
        int j = i - iLookAhead + YYWILDCARD;
        assert( j<(int)(sizeof(yy_lookahead)/sizeof(yy_lookahead[0])) );
        if( yy_lookahead[j]==YYWILDCARD && iLookAhead>0 ){
#ifndef NDEBUG
          if( yyTraceFILE ){
            fprintf(yyTraceFILE, "%sWILDCARD %s => %s\n",
               yyTracePrompt, yyTokenName[iLookAhead],
               yyTokenName[YYWILDCARD]);
          }
#endif /* NDEBUG */
          return yy_action[j];
        }
      }
#endif /* YYWILDCARD */
      return yy_default[stateno];
    }else{
      assert( i>=0 && i<(int)(sizeof(yy_action)/sizeof(yy_action[0])) );
      return yy_action[i];
    }
  }while(1);
}

/*
** Find the appropriate action for a parser given the non-terminal
** look-ahead token iLookAhead.
*/
static YYACTIONTYPE yy_find_reduce_action(
  YYACTIONTYPE stateno,     /* Current state number */
  YYCODETYPE iLookAhead     /* The look-ahead token */
){
  int i;
#ifdef YYERRORSYMBOL
  if( stateno>YY_REDUCE_COUNT ){
    return yy_default[stateno];
  }
#else
  assert( stateno<=YY_REDUCE_COUNT );
#endif
  i = yy_reduce_ofst[stateno];
  assert( iLookAhead!=YYNOCODE );
  i += iLookAhead;
#ifdef YYERRORSYMBOL
  if( i<0 || i>=YY_ACTTAB_COUNT || yy_lookahead[i]!=iLookAhead ){
    return yy_default[stateno];
  }
#else
  assert( i>=0 && i<YY_ACTTAB_COUNT );
  assert( yy_lookahead[i]==iLookAhead );
#endif
  return yy_action[i];
}

/*
** The following routine is called if the stack overflows.
*/
static void yyStackOverflow(yyParser *yypParser){
   ParseARG_FETCH
   ParseCTX_FETCH
#ifndef NDEBUG
   if( yyTraceFILE ){
     fprintf(yyTraceFILE,"%sStack Overflow!\n",yyTracePrompt);
   }
#endif
   while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
   /* Here code is inserted which will execute if the parser
   ** stack every overflows */
/******** Begin %stack_overflow code ******************************************/
/******** End %stack_overflow code ********************************************/
   ParseARG_STORE /* Suppress warning about unused %extra_argument var */
   ParseCTX_STORE
}

/*
** Print tracing information for a SHIFT action
*/
#ifndef NDEBUG
static void yyTraceShift(yyParser *yypParser, int yyNewState, const char *zTag){
  if( yyTraceFILE ){
    if( yyNewState<YYNSTATE ){
      fprintf(yyTraceFILE,"%s%s '%s', go to state %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState);
    }else{
      fprintf(yyTraceFILE,"%s%s '%s', pending reduce %d\n",
         yyTracePrompt, zTag, yyTokenName[yypParser->yytos->major],
         yyNewState - YY_MIN_REDUCE);
    }
  }
}
#else
# define yyTraceShift(X,Y,Z)
#endif

/*
** Perform a shift action.
*/
static void yy_shift(
  yyParser *yypParser,          /* The parser to be shifted */
  YYACTIONTYPE yyNewState,      /* The new state to shift in */
  YYCODETYPE yyMajor,           /* The major token to shift in */
  ParseTOKENTYPE yyMinor        /* The minor token to shift in */
){
  yyStackEntry *yytos;
  yypParser->yytos++;
#ifdef YYTRACKMAXSTACKDEPTH
  if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
    yypParser->yyhwm++;
    assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack) );
  }
#endif
#if YYSTACKDEPTH>0 
  if( yypParser->yytos>yypParser->yystackEnd ){
    yypParser->yytos--;
    yyStackOverflow(yypParser);
    return;
  }
#else
  if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz] ){
    if( yyGrowStack(yypParser) ){
      yypParser->yytos--;
      yyStackOverflow(yypParser);
      return;
    }
  }
#endif
  if( yyNewState > YY_MAX_SHIFT ){
    yyNewState += YY_MIN_REDUCE - YY_MIN_SHIFTREDUCE;
  }
  yytos = yypParser->yytos;
  yytos->stateno = yyNewState;
  yytos->major = yyMajor;
  yytos->minor.yy0 = yyMinor;
  yyTraceShift(yypParser, yyNewState, "Shift");
}

/* For rule J, yyRuleInfoLhs[J] contains the symbol on the left-hand side
** of that rule */
static const YYCODETYPE yyRuleInfoLhs[] = {
    72,  /* (0) package ::= bindings */
    76,  /* (1) bindings ::= binding */
    76,  /* (2) bindings ::= bindings binding */
    73,  /* (3) binding ::= FldName String */
    73,  /* (4) binding ::= FldName COLON string3 */
    73,  /* (5) binding ::= FldName COLON LBRACKET stringlist RBRACKET */
    73,  /* (6) binding ::= CmdListFld LBRACKET cmdlist RBRACKET */
    73,  /* (7) binding ::= INSTALL LBRACKET cmdlist RBRACKET */
    73,  /* (8) binding ::= RUNTEST LBRACKET cmdlist RBRACKET */
    78,  /* (9) cmdlist ::= */
    78,  /* (10) cmdlist ::= cmdlist cmd */
    79,  /* (11) cmd ::= LBRACKET args RBRACKET */
    79,  /* (12) cmd ::= LBRACKET args RBRACKET filter */
    80,  /* (13) args ::= */
    80,  /* (14) args ::= args arg */
    82,  /* (15) arg ::= String */
    82,  /* (16) arg ::= Varident */
    82,  /* (17) arg ::= filter */
    73,  /* (18) binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET */
    73,  /* (19) binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET */
    75,  /* (20) stringlist ::= String */
    75,  /* (21) stringlist ::= stringlist String */
    83,  /* (22) filtered_package_formulas ::= */
    83,  /* (23) filtered_package_formulas ::= filtered_package_formulas fpf */
    74,  /* (24) fpf ::= fpf LogOp fpf */
    74,  /* (25) fpf ::= LPAREN fpf RPAREN */
    74,  /* (26) fpf ::= PKGNAME fvf_expr */
    74,  /* (27) fpf ::= PKGNAME */
    84,  /* (28) fvf_expr ::= LBRACE fvf RBRACE */
    85,  /* (29) fvf ::= */
    85,  /* (30) fvf ::= fvf logop_fvf */
    86,  /* (31) logop_fvf ::= LogOp fvf */
    85,  /* (32) fvf ::= fvf_base */
    87,  /* (33) fvf_base ::= VERSION */
    81,  /* (34) filter ::= LBRACE pred RBRACE */
    88,  /* (35) pred ::= pred LogOp pred */
    88,  /* (36) pred ::= pterm */
    89,  /* (37) pterm ::= Int */
    88,  /* (38) pred ::= String */
    89,  /* (39) pterm ::= Varident */
    88,  /* (40) pred ::= BANG pred */
    88,  /* (41) pred ::= QMARK pred */
    88,  /* (42) pred ::= LPAREN pred RPAREN */
    88,  /* (43) pred ::= pred RELOP pred */
    77,  /* (44) string3 ::= TQ String3 TQ */
    77,  /* (45) string3 ::= TQ String3 String String3 TQ */
};

/* For rule J, yyRuleInfoNRhs[J] contains the negative of the number
** of symbols on the right-hand side of that rule. */
static const signed char yyRuleInfoNRhs[] = {
   -1,  /* (0) package ::= bindings */
   -1,  /* (1) bindings ::= binding */
   -2,  /* (2) bindings ::= bindings binding */
   -2,  /* (3) binding ::= FldName String */
   -3,  /* (4) binding ::= FldName COLON string3 */
   -5,  /* (5) binding ::= FldName COLON LBRACKET stringlist RBRACKET */
   -4,  /* (6) binding ::= CmdListFld LBRACKET cmdlist RBRACKET */
   -4,  /* (7) binding ::= INSTALL LBRACKET cmdlist RBRACKET */
   -4,  /* (8) binding ::= RUNTEST LBRACKET cmdlist RBRACKET */
    0,  /* (9) cmdlist ::= */
   -2,  /* (10) cmdlist ::= cmdlist cmd */
   -3,  /* (11) cmd ::= LBRACKET args RBRACKET */
   -4,  /* (12) cmd ::= LBRACKET args RBRACKET filter */
    0,  /* (13) args ::= */
   -2,  /* (14) args ::= args arg */
   -1,  /* (15) arg ::= String */
   -1,  /* (16) arg ::= Varident */
   -1,  /* (17) arg ::= filter */
   -5,  /* (18) binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET */
   -5,  /* (19) binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET */
   -1,  /* (20) stringlist ::= String */
   -2,  /* (21) stringlist ::= stringlist String */
    0,  /* (22) filtered_package_formulas ::= */
   -2,  /* (23) filtered_package_formulas ::= filtered_package_formulas fpf */
   -3,  /* (24) fpf ::= fpf LogOp fpf */
   -3,  /* (25) fpf ::= LPAREN fpf RPAREN */
   -2,  /* (26) fpf ::= PKGNAME fvf_expr */
   -1,  /* (27) fpf ::= PKGNAME */
   -3,  /* (28) fvf_expr ::= LBRACE fvf RBRACE */
    0,  /* (29) fvf ::= */
   -2,  /* (30) fvf ::= fvf logop_fvf */
   -2,  /* (31) logop_fvf ::= LogOp fvf */
   -1,  /* (32) fvf ::= fvf_base */
   -1,  /* (33) fvf_base ::= VERSION */
   -3,  /* (34) filter ::= LBRACE pred RBRACE */
   -3,  /* (35) pred ::= pred LogOp pred */
   -1,  /* (36) pred ::= pterm */
   -1,  /* (37) pterm ::= Int */
   -1,  /* (38) pred ::= String */
   -1,  /* (39) pterm ::= Varident */
   -2,  /* (40) pred ::= BANG pred */
   -2,  /* (41) pred ::= QMARK pred */
   -3,  /* (42) pred ::= LPAREN pred RPAREN */
   -3,  /* (43) pred ::= pred RELOP pred */
   -3,  /* (44) string3 ::= TQ String3 TQ */
   -5,  /* (45) string3 ::= TQ String3 String String3 TQ */
};

static void yy_accept(yyParser*);  /* Forward Declaration */

/*
** Perform a reduce action and the shift that must immediately
** follow the reduce.
**
** The yyLookahead and yyLookaheadToken parameters provide reduce actions
** access to the lookahead token (if any).  The yyLookahead will be YYNOCODE
** if the lookahead token has already been consumed.  As this procedure is
** only called from one place, optimizing compilers will in-line it, which
** means that the extra parameters have no performance impact.
*/
static YYACTIONTYPE yy_reduce(
  yyParser *yypParser,         /* The parser */
  unsigned int yyruleno,       /* Number of the rule by which to reduce */
  int yyLookahead,             /* Lookahead token, or YYNOCODE if none */
  ParseTOKENTYPE yyLookaheadToken  /* Value of the lookahead token */
  ParseCTX_PDECL                   /* %extra_context */
){
  int yygoto;                     /* The next state */
  YYACTIONTYPE yyact;             /* The next action */
  yyStackEntry *yymsp;            /* The top of the parser's stack */
  int yysize;                     /* Amount to pop the stack */
  ParseARG_FETCH
  (void)yyLookahead;
  (void)yyLookaheadToken;
  yymsp = yypParser->yytos;
  assert( yyruleno<(int)(sizeof(yyRuleName)/sizeof(yyRuleName[0])) );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yysize = yyRuleInfoNRhs[yyruleno];
    if( yysize ){
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s, pop back to state %d.\n",
        yyTracePrompt,
        yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action",
        yymsp[yysize].stateno);
    }else{
      fprintf(yyTraceFILE, "%sReduce %d [%s]%s.\n",
        yyTracePrompt, yyruleno, yyRuleName[yyruleno],
        yyruleno<YYNRULE_WITH_ACTION ? "" : " without external action");
    }
  }
#endif /* NDEBUG */

  /* Check that the stack is large enough to grow by a single entry
  ** if the RHS of the rule is empty.  This ensures that there is room
  ** enough on the stack to push the LHS value */
  if( yyRuleInfoNRhs[yyruleno]==0 ){
#ifdef YYTRACKMAXSTACKDEPTH
    if( (int)(yypParser->yytos - yypParser->yystack)>yypParser->yyhwm ){
      yypParser->yyhwm++;
      assert( yypParser->yyhwm == (int)(yypParser->yytos - yypParser->yystack));
    }
#endif
#if YYSTACKDEPTH>0 
    if( yypParser->yytos>=yypParser->yystackEnd ){
      yyStackOverflow(yypParser);
      /* The call to yyStackOverflow() above pops the stack until it is
      ** empty, causing the main parser loop to exit.  So the return value
      ** is never used and does not matter. */
      return 0;
    }
#else
    if( yypParser->yytos>=&yypParser->yystack[yypParser->yystksz-1] ){
      if( yyGrowStack(yypParser) ){
        yyStackOverflow(yypParser);
        /* The call to yyStackOverflow() above pops the stack until it is
        ** empty, causing the main parser loop to exit.  So the return value
        ** is never used and does not matter. */
        return 0;
      }
      yymsp = yypParser->yytos;
    }
#endif
  }

  switch( yyruleno ){
  /* Beginning here are the reduction cases.  A typical example
  ** follows:
  **   case 0:
  **  #line <lineno> <grammarfile>
  **     { ... }           // User supplied code
  **  #line <lineno> <thisfile>
  **     break;
  */
/********** Begin reduce actions **********************************************/
        YYMINORTYPE yylhsminor;
      case 0: /* package ::= bindings */
#line 182 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "Pkg src: %s", opam_parse_state->pkg->src);
    LOG_DEBUG(0, " bindings ct: %d",
              HASH_CNT(hh, opam_parse_state->pkg->bindings));
    struct opam_binding_s *b;
    for (b = opam_parse_state->pkg->bindings;
         b != NULL;
         b = b->hh.next) {
        LOG_DEBUG(0, "\t%s: %s", b->name, b->val);
    }
}
#line 1280 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 1: /* bindings ::= binding */
#line 194 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "One binding", "");
}
#line 1287 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 2: /* bindings ::= bindings binding */
#line 201 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDINGS ct: %d",
           HASH_CNT(hh, opam_parse_state->pkg->bindings));
    /* no need to do anything, opam_parse_state->pkg->bindings already
       contains all bindings */
    yylhsminor.yy0 = yymsp[-1].minor.yy0;
}
#line 1298 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 3: /* binding ::= FldName String */
#line 209 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING: %s: %s", yymsp[-1].minor.yy0.s, yymsp[0].minor.yy0.s);
    /* create a binding and add it to the pkg hashmap */
    yylhsminor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yylhsminor.yy29->name = yymsp[-1].minor.yy0.s;
    yylhsminor.yy29->t = BINDING_STRING;
    yylhsminor.yy29->val = strdup(yymsp[0].minor.yy0.s);
    HASH_ADD_KEYPTR(hh, // opam_parse_state->pkg->bindings->hh,
                    opam_parse_state->pkg->bindings,
                    yylhsminor.yy29->name, strlen(yylhsminor.yy29->name), yylhsminor.yy29);
}
#line 1314 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy29 = yylhsminor.yy29;
        break;
      case 4: /* binding ::= FldName COLON string3 */
#line 221 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING: %s: %s", yymsp[-2].minor.yy0.s, yymsp[0].minor.yy0.s);
    /* create a binding and add it to the pkg hashmap */
    yylhsminor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yylhsminor.yy29->name = yymsp[-2].minor.yy0.s;
    yylhsminor.yy29->t = BINDING_STRING;
    yylhsminor.yy29->val = strdup(yymsp[0].minor.yy0.s);
    HASH_ADD_KEYPTR(hh, // opam_parse_state->pkg->bindings->hh,
                    opam_parse_state->pkg->bindings,
                    yylhsminor.yy29->name, strlen(yylhsminor.yy29->name), yylhsminor.yy29);
}
#line 1330 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-2].minor.yy29 = yylhsminor.yy29;
        break;
      case 5: /* binding ::= FldName COLON LBRACKET stringlist RBRACKET */
#line 233 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING stringlist %s, ct: %d",
           yymsp[-4].minor.yy0.s, utarray_len(yymsp[-1].minor.yy62));
    /* create a binding and add it to the pkg hashmap */
    yylhsminor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yylhsminor.yy29->name = yymsp[-4].minor.yy0.s;
    yylhsminor.yy29->t = BINDING_STRINGLIST;
    yylhsminor.yy29->val = (void*)yymsp[-1].minor.yy62;
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->bindings,
                    yylhsminor.yy29->name, strlen(yylhsminor.yy29->name), yylhsminor.yy29);
#if YYDEBUG
    LOG_DEBUG(0, "BINDING stringlist val ct: %d",
           utarray_len((UT_array*)yylhsminor.yy29->val));
#endif
}
#line 1351 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-4].minor.yy29 = yylhsminor.yy29;
        break;
      case 6: /* binding ::= CmdListFld LBRACKET cmdlist RBRACKET */
#line 255 "lib/parser/syntaxis/opam_syntaxis.y"
{
    /* BUILD LBRACKET cmdlist(yymsp[-1].minor.yy0) RBRACKET . { */
    LOG_DEBUG(0, "build [cmdlist]", "");
    // for each cmd in cmdlist, print the args
    int ct = utarray_len(yymsp[-1].minor.yy0.cmds);
    LOG_DEBUG(0, "cmd ct: %d", ct);
    struct opam_cmd_s *cmd = NULL;
    for(cmd=(struct opam_cmd_s*)utarray_front(yymsp[-1].minor.yy0.cmds);
        cmd!=NULL;
        cmd=(struct opam_cmd_s*)utarray_next(yymsp[-1].minor.yy0.cmds, cmd)) {
        ct = utarray_len(cmd->args);
        LOG_DEBUG(0, "cmd args ct: %d", ct);
        struct opam_arg_s *arg = NULL;
        for(arg=(struct opam_arg_s*)utarray_front(cmd->args);
            arg!=NULL;
            arg=(struct opam_arg_s*)utarray_next(cmd->args, arg)) {
            LOG_DEBUG(0, "\t%s", arg->val);
        }
    }
    /* opam_parse_state->pkg->bindings, */
    yymsp[-3].minor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-3].minor.yy29->name = strndup("build", 5);
    yymsp[-3].minor.yy29->t = BINDING_BUILD;
    yymsp[-3].minor.yy29->val = yymsp[-1].minor.yy0.cmds;
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->bindings,
                    yymsp[-3].minor.yy29->name, strlen(yymsp[-3].minor.yy29->name), yymsp[-3].minor.yy29);
}
#line 1384 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 7: /* binding ::= INSTALL LBRACKET cmdlist RBRACKET */
#line 285 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING install", "");
    yymsp[-3].minor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-3].minor.yy29->name = strndup("install", 7);
    yymsp[-3].minor.yy29->t = BINDING_BUILD;
    /* yymsp[-3].minor.yy29->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->bindings,
                    yymsp[-3].minor.yy29->name, strlen(yymsp[-3].minor.yy29->name), yymsp[-3].minor.yy29);
}
#line 1398 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 8: /* binding ::= RUNTEST LBRACKET cmdlist RBRACKET */
#line 297 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "BINDING run-test", "");
    yymsp[-3].minor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-3].minor.yy29->name = strndup("run-test", 8);
    yymsp[-3].minor.yy29->t = BINDING_BUILD;
    /* yymsp[-3].minor.yy29->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->bindings,
                    yymsp[-3].minor.yy29->name, strlen(yymsp[-3].minor.yy29->name), yymsp[-3].minor.yy29);
}
#line 1412 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 9: /* cmdlist ::= */
#line 308 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmdlist (empty)", "");
    UT_array *cmds;
    utarray_new(cmds, &opam_cmd_icd);
    yymsp[1].minor.yy0.cmds = cmds;
}
#line 1422 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 10: /* cmdlist ::= cmdlist cmd */
#line 315 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmdlist cmd", "");
    DUMP_ARGS(yymsp[0].minor.yy0.cmd->args);
    utarray_push_back(yymsp[-1].minor.yy0.cmds, yymsp[0].minor.yy0.cmd);
    yylhsminor.yy0.cmds = yymsp[-1].minor.yy0.cmds;
}
#line 1432 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 11: /* cmd ::= LBRACKET args RBRACKET */
#line 322 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmd:: [args]", "");
    struct opam_cmd_s *cmd = (struct opam_cmd_s*)malloc(
                       sizeof(struct opam_cmd_s));
    cmd->args = yymsp[-1].minor.yy0.args;
    yymsp[-2].minor.yy0.cmd = cmd;
    DUMP_ARGS(yymsp[-2].minor.yy0.cmd->args);
}
#line 1445 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 12: /* cmd ::= LBRACKET args RBRACKET filter */
#line 331 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "cmd:: [args] filter", "");
    struct opam_cmd_s *cmd = (struct opam_cmd_s*)malloc(
                       sizeof(struct opam_cmd_s));
    cmd->args = yymsp[-2].minor.yy0.args;
    cmd->filter = yymsp[0].minor.yy0.filter;
    yymsp[-3].minor.yy0.cmd = cmd;
}
#line 1457 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 13: /* args ::= */
#line 340 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "args (empty)", "");
    UT_array *args;
    utarray_new(args, &opam_arg_icd);
    /* struct opam_arg_s *arg = (struct opam_arg_s*)malloc( */
    /*                    sizeof(struct opam_arg_s)); */
    /* arg->val = strdup("testarg"); */
    /* arg->t   = 0; */
    /* utarray_push_back(args, arg); */
    DUMP_ARGS(args);
    yymsp[1].minor.yy0.args = args;
}
#line 1473 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 14: /* args ::= args arg */
#line 353 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "args arg val %s, type %d", yymsp[0].minor.yy0.arg->val, yymsp[0].minor.yy0.arg->t);
    DUMP_ARGS(yymsp[-1].minor.yy0.args);
    utarray_push_back(yymsp[-1].minor.yy0.args, yymsp[0].minor.yy0.arg);
    DUMP_ARGS(yymsp[-1].minor.yy0.args);
    yylhsminor.yy0 = yymsp[-1].minor.yy0;
}
#line 1484 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy0 = yylhsminor.yy0;
        break;
      case 15: /* arg ::= String */
#line 361 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "string arg: %s", yymsp[0].minor.yy0.s);
    struct opam_arg_s *arg = (struct opam_arg_s*)malloc(
                       sizeof(struct opam_arg_s));
    arg->val = strdup(yymsp[0].minor.yy0.s);
    arg->t   = 0;
    yylhsminor.yy0.arg = arg;
}
#line 1497 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 16: /* arg ::= Varident */
#line 370 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "var arg: %s", yymsp[0].minor.yy0.s);
    struct opam_arg_s *arg = (struct opam_arg_s*)malloc(
                       sizeof(struct opam_arg_s));
    arg->val = strdup(yymsp[0].minor.yy0.s);
    arg->t   = 1;
    yylhsminor.yy0.arg = arg;
}
#line 1510 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[0].minor.yy0 = yylhsminor.yy0;
        break;
      case 17: /* arg ::= filter */
#line 379 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "filter arg", "");
}
#line 1518 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 18: /* binding ::= DEPENDS COLON LBRACKET filtered_package_formulas RBRACKET */
#line 387 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "BINDING depends", "");
#endif
    yymsp[-4].minor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-4].minor.yy29->name = strndup("depends", 7);
    yymsp[-4].minor.yy29->t = BINDING_DEPENDS;
    /* yymsp[-4].minor.yy29->val = ... will be list of pkgs */
    /* so here, alloc a UT hash table to hold the list */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->bindings,
                    yymsp[-4].minor.yy29->name,
                    strlen(yymsp[-4].minor.yy29->name),
                    yymsp[-4].minor.yy29);
}
#line 1537 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 19: /* binding ::= CONFLICTS COLON LBRACKET filtered_package_formulas RBRACKET */
#line 404 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "BINDING conflicts", "");
#endif
    yymsp[-4].minor.yy29 = calloc(sizeof(struct opam_binding_s), 1);
    yymsp[-4].minor.yy29->name = strndup("conflicts", 9);
    yymsp[-4].minor.yy29->t = BINDING_DEPENDS;
    /* yymsp[-4].minor.yy29->val =  */
    HASH_ADD_KEYPTR(hh,
                    opam_parse_state->pkg->bindings,
                    yymsp[-4].minor.yy29->name, strlen(yymsp[-4].minor.yy29->name), yymsp[-4].minor.yy29);
}
#line 1553 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 20: /* stringlist ::= String */
#line 417 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
    LOG_DEBUG(0, "STRINGLIST single: %s", yymsp[0].minor.yy0.s);
#endif
    utarray_new(yylhsminor.yy62, &ut_str_icd);
    utarray_push_back(yylhsminor.yy62, &yymsp[0].minor.yy0.s);
}
#line 1564 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[0].minor.yy62 = yylhsminor.yy62;
        break;
      case 21: /* stringlist ::= stringlist String */
#line 425 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
    LOG_DEBUG(0, "STRINGLIST multiple, ct: %d; new: %s",
           utarray_len(yymsp[-1].minor.yy62), yymsp[0].minor.yy0.s);
#endif
    utarray_push_back(yymsp[-1].minor.yy62, &yymsp[0].minor.yy0.s);
    yylhsminor.yy62 = yymsp[-1].minor.yy62;
}
#line 1577 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
  yymsp[-1].minor.yy62 = yylhsminor.yy62;
        break;
      case 22: /* filtered_package_formulas ::= */
#line 448 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "filtered_package_formulas: null", "");
#endif
    }
#line 1587 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 23: /* filtered_package_formulas ::= filtered_package_formulas fpf */
#line 454 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "filtered_package_formulas leftrec", "");
#endif
    }
#line 1596 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 24: /* fpf ::= fpf LogOp fpf */
#line 460 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fpf: fpf LogOp fpf", "");
#endif
    }
#line 1605 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 25: /* fpf ::= LPAREN fpf RPAREN */
#line 466 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fpf: (fpf)", "");
#endif
    }
#line 1614 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 26: /* fpf ::= PKGNAME fvf_expr */
#line 472 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(1, "fpf: pkgname fvf_expr:**************** %s",
                  yymsp[-1].minor.yy0.s);
    }
#line 1622 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 27: /* fpf ::= PKGNAME */
#line 477 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(0, "fpf: **************** pkgname: %s", yymsp[0].minor.yy0.s);
        /* Deps = calloc(sizeof(struct opam_binding_s), 1); */
        /*  */
    }
#line 1631 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 28: /* fvf_expr ::= LBRACE fvf RBRACE */
#line 484 "lib/parser/syntaxis/opam_syntaxis.y"
{
      LOG_DEBUG(0, "fvf_expr: braces", "");
    }
#line 1638 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 29: /* fvf ::= */
#line 500 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: null", "");
#endif
    }
#line 1647 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 30: /* fvf ::= fvf logop_fvf */
#line 506 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: fvf logop_fvf", "");
#endif
    }
#line 1656 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 31: /* logop_fvf ::= LogOp fvf */
#line 512 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: fvf logop fvf", "");
#endif
    }
#line 1665 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 32: /* fvf ::= fvf_base */
#line 544 "lib/parser/syntaxis/opam_syntaxis.y"
{
#if YYDEBUG
        LOG_DEBUG(0, "fvf: fvf_base", "");
#endif
       }
#line 1674 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 33: /* fvf_base ::= VERSION */
#line 556 "lib/parser/syntaxis/opam_syntaxis.y"
{ // treated as <string>
#if YYDEBUG
        LOG_DEBUG(0, "fvf_base: version", "");
#endif
    }
#line 1683 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 34: /* filter ::= LBRACE pred RBRACE */
#line 626 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "{pred}", "");
}
#line 1690 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 35: /* pred ::= pred LogOp pred */
#line 629 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "compound pred: <pred> %s <pred>", yymsp[-1].minor.yy0.s);
}
#line 1697 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 36: /* pred ::= pterm */
#line 633 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred", "");
}
#line 1704 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 37: /* pterm ::= Int */
#line 639 "lib/parser/syntaxis/opam_syntaxis.y"
{
/* pred ::= Int(yymsp[0].minor.yy0) . { */
    LOG_DEBUG(0, "pred int: %s", yymsp[0].minor.yy0.s);
}
#line 1712 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 38: /* pred ::= String */
#line 643 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred yymsp[0].minor.yy0: %s", yymsp[0].minor.yy0.s);
}
#line 1719 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 39: /* pterm ::= Varident */
#line 646 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pterm var: %s", yymsp[0].minor.yy0.s);
}
#line 1726 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 40: /* pred ::= BANG pred */
#line 649 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(0, "pred: BANG filter", "");
}
#line 1733 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 41: /* pred ::= QMARK pred */
#line 652 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred: QMARK pred", "");
}
#line 1740 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 42: /* pred ::= LPAREN pred RPAREN */
#line 655 "lib/parser/syntaxis/opam_syntaxis.y"
{
    LOG_DEBUG(0, "pred: (pred)", "");
}
#line 1747 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 43: /* pred ::= pred RELOP pred */
#line 658 "lib/parser/syntaxis/opam_syntaxis.y"
{
        LOG_DEBUG(0, "pred: pred %s pred", yymsp[-1].minor.yy0.s);
}
#line 1754 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      case 44: /* string3 ::= TQ String3 TQ */
      case 45: /* string3 ::= TQ String3 String String3 TQ */ yytestcase(yyruleno==45);
#line 704 "lib/parser/syntaxis/opam_syntaxis.y"
{
}
#line 1761 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
        break;
      default:
        break;
/********** End reduce actions ************************************************/
  };
  assert( yyruleno<sizeof(yyRuleInfoLhs)/sizeof(yyRuleInfoLhs[0]) );
  yygoto = yyRuleInfoLhs[yyruleno];
  yysize = yyRuleInfoNRhs[yyruleno];
  yyact = yy_find_reduce_action(yymsp[yysize].stateno,(YYCODETYPE)yygoto);

  /* There are no SHIFTREDUCE actions on nonterminals because the table
  ** generator has simplified them to pure REDUCE actions. */
  assert( !(yyact>YY_MAX_SHIFT && yyact<=YY_MAX_SHIFTREDUCE) );

  /* It is not possible for a REDUCE to be followed by an error */
  assert( yyact!=YY_ERROR_ACTION );

  yymsp += yysize+1;
  yypParser->yytos = yymsp;
  yymsp->stateno = (YYACTIONTYPE)yyact;
  yymsp->major = (YYCODETYPE)yygoto;
  yyTraceShift(yypParser, yyact, "... then shift");
  return yyact;
}

/*
** The following code executes when the parse fails
*/
#ifndef YYNOERRORRECOVERY
static void yy_parse_failed(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sFail!\n",yyTracePrompt);
  }
#endif
  while( yypParser->yytos>yypParser->yystack ) yy_pop_parser_stack(yypParser);
  /* Here code is inserted which will be executed whenever the
  ** parser fails */
/************ Begin %parse_failure code ***************************************/
#line 174 "lib/parser/syntaxis/opam_syntaxis.y"

    LOG_ERROR(0, "Giving up.  Parser is hopelessly lost... %d",
    yypParser->yyerrcnt);
#line 1809 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
/************ End %parse_failure code *****************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}
#endif /* YYNOERRORRECOVERY */

/*
** The following code executes when a syntax error first occurs.
*/
static void yy_syntax_error(
  yyParser *yypParser,           /* The parser */
  int yymajor,                   /* The major type of the error token */
  ParseTOKENTYPE yyminor         /* The minor type of the error token */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#define TOKEN yyminor
/************ Begin %syntax_error code ****************************************/
#line 151 "lib/parser/syntaxis/opam_syntaxis.y"

    LOG_ERROR(0, RED "SYNTAX ERROR" CRESET " yymajor: %d", yymajor);
    LOG_ERROR(0, RED "tos.stateno" CRESET ": %d", yypParser->yytos->stateno);
    LOG_ERROR(0, RED "tos.major" CRESET ": %d", yypParser->yytos->major);
    LOG_ERROR(0, RED "tos.minor" CRESET ": %d", yypParser->yytos->minor);
/* args passed:
   yyParser *yypParser, /\* The parser *\/
   int yymajor, /\* The major type of the error token *\/
   ParseTOKENTYPE yyminor /\* The minor type of the error token *\/
   ParseTOKENTYPE is union opam_token_u
 */

                            
                      
     
     log_error("trying to recover...");
      
#line 1846 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
/************ End %syntax_error code ******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/*
** The following is executed when the parser accepts
*/
static void yy_accept(
  yyParser *yypParser           /* The parser */
){
  ParseARG_FETCH
  ParseCTX_FETCH
#ifndef NDEBUG
  if( yyTraceFILE ){
    fprintf(yyTraceFILE,"%sAccept!\n",yyTracePrompt);
  }
#endif
#ifndef YYNOERRORRECOVERY
  yypParser->yyerrcnt = -1;
#endif
  assert( yypParser->yytos==yypParser->yystack );
  /* Here code is inserted which will be executed whenever the
  ** parser accepts */
/*********** Begin %parse_accept code *****************************************/
#line 170 "lib/parser/syntaxis/opam_syntaxis.y"

    LOG_TRACE(0, "Parsing complete", "");
#line 1875 "bazel-out/darwin_arm64-fastbuild/bin/lib/parser/syntaxis/opam_syntaxis.c"
/*********** End %parse_accept code *******************************************/
  ParseARG_STORE /* Suppress warning about unused %extra_argument variable */
  ParseCTX_STORE
}

/* The main parser program.
** The first argument is a pointer to a structure obtained from
** "ParseAlloc" which describes the current state of the parser.
** The second argument is the major token number.  The third is
** the minor token.  The fourth optional argument is whatever the
** user wants (and specified in the grammar) and is available for
** use by the action routines.
**
** Inputs:
** <ul>
** <li> A pointer to the parser (an opaque structure.)
** <li> The major token number.
** <li> The minor token number.
** <li> An option argument of a grammar-specified type.
** </ul>
**
** Outputs:
** None.
*/
void Parse(
  void *yyp,                   /* The parser */
  int yymajor,                 /* The major token code number */
  ParseTOKENTYPE yyminor       /* The value for the token */
  ParseARG_PDECL               /* Optional %extra_argument parameter */
){
  YYMINORTYPE yyminorunion;
  YYACTIONTYPE yyact;   /* The parser action. */
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  int yyendofinput;     /* True if we are at the end of input */
#endif
#ifdef YYERRORSYMBOL
  int yyerrorhit = 0;   /* True if yymajor has invoked an error */
#endif
  yyParser *yypParser = (yyParser*)yyp;  /* The parser */
  ParseCTX_FETCH
  ParseARG_STORE

  assert( yypParser->yytos!=0 );
#if !defined(YYERRORSYMBOL) && !defined(YYNOERRORRECOVERY)
  yyendofinput = (yymajor==0);
#endif

  yyact = yypParser->yytos->stateno;
#ifndef NDEBUG
  if( yyTraceFILE ){
    if( yyact < YY_MIN_REDUCE ){
      fprintf(yyTraceFILE,"%sInput '%s' in state %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact);
    }else{
      fprintf(yyTraceFILE,"%sInput '%s' with pending reduce %d\n",
              yyTracePrompt,yyTokenName[yymajor],yyact-YY_MIN_REDUCE);
    }
  }
#endif

  do{
    assert( yyact==yypParser->yytos->stateno );
    yyact = yy_find_shift_action((YYCODETYPE)yymajor,yyact);
    if( yyact >= YY_MIN_REDUCE ){
      yyact = yy_reduce(yypParser,yyact-YY_MIN_REDUCE,yymajor,
                        yyminor ParseCTX_PARAM);
    }else if( yyact <= YY_MAX_SHIFTREDUCE ){
      yy_shift(yypParser,yyact,(YYCODETYPE)yymajor,yyminor);
#ifndef YYNOERRORRECOVERY
      yypParser->yyerrcnt--;
#endif
      break;
    }else if( yyact==YY_ACCEPT_ACTION ){
      yypParser->yytos--;
      yy_accept(yypParser);
      return;
    }else{
      assert( yyact == YY_ERROR_ACTION );
      yyminorunion.yy0 = yyminor;
#ifdef YYERRORSYMBOL
      int yymx;
#endif
#ifndef NDEBUG
      if( yyTraceFILE ){
        fprintf(yyTraceFILE,"%sSyntax Error!\n",yyTracePrompt);
      }
#endif
#ifdef YYERRORSYMBOL
      /* A syntax error has occurred.
      ** The response to an error depends upon whether or not the
      ** grammar defines an error token "ERROR".  
      **
      ** This is what we do if the grammar does define ERROR:
      **
      **  * Call the %syntax_error function.
      **
      **  * Begin popping the stack until we enter a state where
      **    it is legal to shift the error symbol, then shift
      **    the error symbol.
      **
      **  * Set the error count to three.
      **
      **  * Begin accepting and shifting new tokens.  No new error
      **    processing will occur until three tokens have been
      **    shifted successfully.
      **
      */
      if( yypParser->yyerrcnt<0 ){
        yy_syntax_error(yypParser,yymajor,yyminor);
      }
      yymx = yypParser->yytos->major;
      if( yymx==YYERRORSYMBOL || yyerrorhit ){
#ifndef NDEBUG
        if( yyTraceFILE ){
          fprintf(yyTraceFILE,"%sDiscard input token %s\n",
             yyTracePrompt,yyTokenName[yymajor]);
        }
#endif
        yy_destructor(yypParser, (YYCODETYPE)yymajor, &yyminorunion);
        yymajor = YYNOCODE;
      }else{
        while( yypParser->yytos >= yypParser->yystack
            && (yyact = yy_find_reduce_action(
                        yypParser->yytos->stateno,
                        YYERRORSYMBOL)) > YY_MAX_SHIFTREDUCE
        ){
          yy_pop_parser_stack(yypParser);
        }
        if( yypParser->yytos < yypParser->yystack || yymajor==0 ){
          yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
          yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
          yypParser->yyerrcnt = -1;
#endif
          yymajor = YYNOCODE;
        }else if( yymx!=YYERRORSYMBOL ){
          yy_shift(yypParser,yyact,YYERRORSYMBOL,yyminor);
        }
      }
      yypParser->yyerrcnt = 3;
      yyerrorhit = 1;
      if( yymajor==YYNOCODE ) break;
      yyact = yypParser->yytos->stateno;
#elif defined(YYNOERRORRECOVERY)
      /* If the YYNOERRORRECOVERY macro is defined, then do not attempt to
      ** do any kind of error recovery.  Instead, simply invoke the syntax
      ** error routine and continue going as if nothing had happened.
      **
      ** Applications can set this macro (for example inside %include) if
      ** they intend to abandon the parse upon the first syntax error seen.
      */
      yy_syntax_error(yypParser,yymajor, yyminor);
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      break;
#else  /* YYERRORSYMBOL is not defined */
      /* This is what we do if the grammar does not define ERROR:
      **
      **  * Report an error message, and throw away the input token.
      **
      **  * If the input token is $, then fail the parse.
      **
      ** As before, subsequent error messages are suppressed until
      ** three input tokens have been successfully shifted.
      */
      if( yypParser->yyerrcnt<=0 ){
        yy_syntax_error(yypParser,yymajor, yyminor);
      }
      yypParser->yyerrcnt = 3;
      yy_destructor(yypParser,(YYCODETYPE)yymajor,&yyminorunion);
      if( yyendofinput ){
        yy_parse_failed(yypParser);
#ifndef YYNOERRORRECOVERY
        yypParser->yyerrcnt = -1;
#endif
      }
      break;
#endif
    }
  }while( yypParser->yytos>yypParser->yystack );
#ifndef NDEBUG
  if( yyTraceFILE ){
    yyStackEntry *i;
    char cDiv = '[';
    fprintf(yyTraceFILE,"%sReturn. Stack=",yyTracePrompt);
    for(i=&yypParser->yystack[1]; i<=yypParser->yytos; i++){
      fprintf(yyTraceFILE,"%c%s", cDiv, yyTokenName[i->major]);
      cDiv = ' ';
    }
    fprintf(yyTraceFILE,"]\n");
  }
#endif
  return;
}

/*
** Return the fallback token corresponding to canonical token iToken, or
** 0 if iToken has no fallback.
*/
int ParseFallback(int iToken){
#ifdef YYFALLBACK
  assert( iToken<(int)(sizeof(yyFallback)/sizeof(yyFallback[0])) );
  return yyFallback[iToken];
#else
  (void)iToken;
  return 0;
#endif
}
